### ISSUE TITLE
Install failing with unmet sinon peer dependency

### ISSUE THREAD

**Issue by indcoder** [greenkeeperio/greenkeeper#394] opened 2017-03-25 19:26 UTC
Im trying to run greenkeerper on my OSS repo but its failing

Details:

1)Machine : Win 10 Pro
2) Error 

`λ npm install-test
- util@0.10.3 node_modules\util
eb-checkin-module@0.1.0 C:\Users\lnovo\Documents\Projects\eb-checkin-module
`-- UNMET PEER DEPENDENCY sinon@2.1.0
  +-- diff@3.2.0
  +-- formatio@1.2.0
  +-- lolex@1.6.0
  +-- path-to-regexp@1.7.0
  | `-- isarray@0.0.1
  +-- samsam@1.2.1
  +-- text-encoding@0.6.4
  `-- type-detect@4.0.0

Crashes with the following error

sinon-as-promised\index.js:14
sinon.behavior.resolves = resolves
                        ^

TypeError: Cannot set property 'resolves' of undefined`

**Comment by Jamil81** [comment] 2017-05-03 11:26
same problem here, did you find a solution yet?

**Comment by boennemann** [comment] 2017-05-21 00:07
I'm not sure what the problem is here, but it seems unrelated to Greenkeeper. I'm going to close this issue to keep our issue tracker clean and actionable.

Happy to reopen upon further explanation.

**Closed by boennemann** 2017-05-21 00:07 UTC
