### ISSUE TITLE
Greekeeper create a `chore` commit instead of a `fix` in Initial PR 

### ISSUE THREAD

**Issue by pvdlg** [greenkeeperio/greenkeeper#568] opened 2017-12-31 06:36 UTC
When the initial PR is created, if it updates `dependencies` (and not only `devDependencies`) it should create a `fix` commit similarly to regular PRs.

However it's not the case, a `chore` commit is created instead.

See semantic-release/apm-config#3 for an example.

**Comment by Arcanemagus** [comment] 2018-01-04 17:50
Duplicate of #555.

**Comment by pvdlg** [comment] 2018-01-04 17:53
I don't think its a duplicate.  #555 is about `chore` being removed from the Angular convention.

This issue is about Greenkeeper not using the rule for commit message, depending if the context is a regular PR or the initial PR.

**Comment by espy** [comment] 2018-01-09 16:33
Another good find, thanks! We’ll make the behaviour consistent between initial and regular PRs, since that seems relatively minor, and then we need to decide whether we stick with Angular and throw out `chore` altogether later.

**Comment by travi** [comment] 2018-01-09 16:40
i was another one caught by the removal of `chore`, but simply switching from the angular convention to https://www.npmjs.com/package/@commitlint/config-conventional gets it back. seems like a reasonable recommendation for most projects so that greenkeeper could keep using `chore` to differentiate between `devDependencies` and `dependencies` updates

**Comment by Arcanemagus** [comment] 2018-06-19 16:50
I believe that https://github.com/greenkeeperio/greenkeeper/pull/612 allows this issue to be closed as the message is now customizable if so desired.

**Closed** 2018-07-10 14:08 UTC
Labels: Bug/Problem
