### ISSUE TITLE
Yarn.lock file not updated

### ISSUE THREAD

**Issue by nojaf** [greenkeeperio/greenkeeper#1125] opened 2019-09-02 09:33 UTC
Hi, I'm bit puzzled why this PR (https://github.com/nojaf/fable-reactstrap/pull/5) didn't include a change for the `yarn.lock` file.
What am I missing to enable this?

**Comment by gr2m** [comment] 2019-09-03 19:03
I think it's a bug with Greenkeeper, I've seen that happening periodically with Greenkeeper. I have the same problem and lots of false positives because of it, with `package-lock.json` in my case

<img width="608" alt="image" src="https://user-images.githubusercontent.com/39992/64201165-dcdac900-ce42-11e9-86ff-8d4955af3b42.png">

**Comment by limonte** [comment] 2019-09-18 18:26
Duplicate of #1118

**Closed** 2019-09-23 12:31 UTC
