### ISSUE TITLE
converts single number semvers to a pinned version

### ISSUE THREAD

**Issue by jonathanong** [greenkeeperio/greenkeeper#103] opened 2016-01-05 22:20 UTC
ex. i had `"bluebird": "2"`. it updated it to `"bluebird": "3.1.1"` when i want it as semver major like `"bluebird": "^3.1.1"`

**Comment by boennemann** [comment] 2016-01-27 15:10
This is a bug, thanks for the report.

**Comment by finnp** [comment] 2016-08-02 14:13
Closing this as a duplicate of  https://github.com/greenkeeperio/greenkeeper/issues/64

**Closed by finnp** 2016-08-02 14:13 UTC
Labels: Bug/Problem
