### ISSUE TITLE
Tips for preventing git conflicts in package.json?

### ISSUE THREAD

**Issue by zeke** [greenkeeperio/greenkeeper#567] opened 2017-12-22 21:13 UTC
This is happening a lot:

<img width="415" alt="screen shot 2017-12-22 at 1 11 22 pm" src="https://user-images.githubusercontent.com/2289/34312527-b4e7ea84-e719-11e7-81ea-8ce05e68d761.png">

Both of those deps are updated quite often, and so I end up having to resolve these conflicts a lot.

Any ideas on simple ways to avoid this?

**Comment by espy** [comment] 2018-01-09 16:05
Thanks for the heads up and sorry for the inconvenience. There’s no workaround on your end I can think of, I’m afraid. 

Just to explain: the old Greenkeeper actually updated all open Greenkeeper branches every time one of them was merged, to prevent just this issue. The problem is that we can’t guarantee these updates will happen fast enough to actually be of use, there are some limiting factors which we have no control over.

Usually people do all open Greenkeeper PRs one after the other, and we simply couldn’t guarantee a consistent experience: sometimes the PRs would be up to date on time, sometimes not.

We may have an opportunity to revisit this soon though, so thanks for letting us know nonetheless :)

**Comment by zeke** [comment] 2018-01-10 05:00
Thanks for the info, @espy. The only thing I can think of is injecting a fake package name that fits alphabetically between the two:

```json
{
  "electron-apps": "1.0.0",
  "electron-between-the-two-bogus-package": "*",
  "electron-i18n": "1.0.0"
}
```

🙈

**Comment by travi** [comment] 2018-01-11 05:34
i have found that getting the PRs merged as quickly as possible helps quite a bit with avoiding conflicts like this. i leverage (an maintain) [greenkeeper-keeper](https://github.com/greenkeeper-keeper) to automatically merge the PRs as long as all the commit checks pass so that they dont wait around until i have the time to do it manually. i wouldnt recommend this approach w/o solid test coverage, but i have found it to be worthwhile for this problem.

even getting things merged quickly does not completely eliminate the issue though because of the many projects that release all of their packages all at the same time (this practice bothers me for many reasons, but this is the biggest pain point i've had as a result from the perspective of a consumer). normally, one of the PRs is able to be merged successfully, but all of the others that surround it then conflict with that merge.

@espy since `greenkeeper-keeper` responds to the `status` webhooks from github, timing wouldnt really be an issue in at least my scenario. i think updating the other PRs after the first one gets successfully merged would work out well for me since it would continue to trigger hooks to after any updates until all the commit statuses pass.

**Comment by janl** [comment] 2018-07-10 14:06
Closing until further feedback / options present themselves

**Closed by janl** 2018-07-10 14:06 UTC
Labels: Feature
