### ISSUE TITLE
Greenkeeper creates branches but no PRs

### ISSUE THREAD

**Issue by TitanNano** [greenkeeperio/greenkeeper#378] opened 2017-02-11 19:03 UTC
Greenpkeeper often creates new branches for updated dependencies, but doesn't create a corresponding PR.
![screen shot 2017-02-11 at 20 02 15](https://cloud.githubusercontent.com/assets/4500858/22856619/11ce05d4-f095-11e6-9e84-2bc9ebdea028.png)
Two branches have been created but no PRs.

**Comment by cebor** [comment] 2017-02-11 21:00
This is the only way greenkeeper can test it versus your ci, it only will create an pr if your ci fails or it does not match your actual semver.

**Comment by TitanNano** [comment] 2017-02-11 21:21
Well the branches could be at least closed if no PR is going to be created... the branch at the bottom is sitting in the repo for 17 hours and nothing happened since then.

**Comment by DiegoRBaquero** [comment] 2017-03-01 02:55
I have repos where semver doesn't match and PR is still not created.

e.g. https://github.com/DiegoRBaquero/V/tree/greenkeeper/standard-9.0.0 while using ^8.6.0, so it should create PR.

**Comment by levsthings** [comment] 2017-05-04 05:54
We're having the same issues in our repository, it has nothing to do with tests passing or version coverage, Greenkeeper regularly branches without creating a PR.

**Comment by ismay** [comment] 2017-05-10 13:28
I've encountered this as well. Some branches for in-range updates with successful tests are never removed (some as much as 2 months old), and sometimes PRs aren't created for branches with packages that have out-of-range updates.

**Comment by boennemann** [comment] 2017-05-21 00:04
Branches lying around without being deleted is definitely not the intended behavior here – sorry about that.
We've recently deployed a fix for this so I hope the problem is gone for good.

Happy to reopen this issue if the problem reappears.

**Closed by boennemann** 2017-05-21 00:04 UTC

**Comment by msafih** [comment] 2017-05-23 03:53
@boennemann Greenkeeper created another dud branch 7 hours ago

https://github.com/hollowverse/hollowverse/branches

The specific branch is `greenkeeper/@types/node-7.0.22`
