### ISSUE TITLE
Does it work with monorepo architecture?

### ISSUE THREAD

**Issue by steelbrain** [greenkeeperio/greenkeeper#166] opened 2016-04-11 08:01 UTC
Just wondering if greenkeeper works with mono repo architecture

If it does not, I would like to request the ability to have `.greenkeeper.json` in project root which has a map of all the packages that points to their roots like

```js
{
  "babel-core": "./packages/babel-core"
}
```

**Comment by boennemann** [comment] 2016-04-13 19:45
Hey @steelbrain,

thanks for your feedback. I'm closing this issue as a duplicate of #139.
Please subscribe to that issue for updates.

Best,
Stephan

**Closed by boennemann** 2016-04-13 19:45 UTC
