### ISSUE TITLE
Proposed version range too liberal

### ISSUE THREAD

**Issue by moll** [greenkeeperio/greenkeeper#254] opened 2016-08-01 08:15 UTC
Hey,

I've been getting some GK PRs on https://github.com/isaacs/json-stringify-safe/pull/19. I noticed they have an unbounded version range. While I don't care for GK myself, I don't think open version ranges are appropriate. Stick to SemVer or mimic what was there before.

Cheers

**Comment by finnp** [comment] 2016-08-01 13:21
Hey,

thank you for reporting this. This is one of the cases we currently do not support properly. The equivalent  `^2.1.0` would work as expected. We're going to improve on this, but there are quite a view edge cases when it comes to version ranges that make this difficult.

**Comment by finnp** [comment] 2016-08-02 14:14
Closing this as a duplicate of https://github.com/greenkeeperio/greenkeeper/issues/64

**Closed by finnp** 2016-08-02 14:14 UTC
Labels: Bug/Problem
