### ISSUE TITLE
Support lerna repositories

### ISSUE THREAD

**Issue by doug-wade** [greenkeeperio/greenkeeper#234] opened 2016-06-29 22:11 UTC
I'd like to use greenkeeper for our monorepo for React Server, but it only updates the top-level package.json, and not the individual package's dependencies.  In [this pull request](https://github.com/redfin/react-server/pull/315), greenkeeper updates the root package.json, but none of the ones in [packages](https://github.com/redfin/react-server/tree/master/packages) (for instance [React Server proper](https://github.com/redfin/react-server/tree/master/packages/react-server/package.json) or our [cli](https://github.com/redfin/react-server/tree/master/packages/react-server-cli/package.json).  We use a tool called [lerna](github.com/lerna/lerna) to manage our monorepo; updating the dependencies with [david](https://github.com/alanshaw/david) would be accomplished as follows: `lerna exec -- david u`

**Comment by janl** [comment] 2016-07-07 10:22
Heya, this is a good feature request. I’m closing this as a duplicate of https://github.com/greenkeeperio/greenkeeper/issues/139

**Closed by janl** 2016-07-07 10:22 UTC
