### ISSUE TITLE
yarn.lock is not being updated

### ISSUE THREAD

**Issue by limonte** [greenkeeperio/greenkeeper#1118] opened 2019-07-15 14:21 UTC
Example: https://github.com/sweetalert2/sweetalert2/pull/1664

### Actual behavior

Only `package.json` is updated

### Expected behavior

Both `package.json` and `yarn.lock` are updated

**Comment by limonte** [comment] 2019-07-19 13:48
another example https://github.com/sweetalert2/sweetalert2/pull/1670

**Comment by EvHaus** [comment] 2019-08-24 20:36
Same problem for me as well. https://github.com/GlobexDesignsInc/eslint-config-globex/pull/2/files

**Comment by Siggnja** [comment] 2019-09-18 16:13
Is there anyone looking into this? We are experiencing the same issue.

**Comment by janl** [comment] 2019-09-23 11:57
Hey all, thanks for all your patience. We’ve deployed a fix for this earlier today that should cover most of the reasons for this issue. If any of you still see this, please send let us know.

**Comment by EvHaus** [comment] 2019-09-23 18:56
Greenkeeper just opened this PR but didn't include a `yarn.lock` update: https://github.com/GlobexDesignsInc/magna.gg/pull/22/files

**Comment by nojaf** [comment] 2019-09-24 05:40
Same here, https://github.com/nojaf/fable-reactstrap/pull/12/files

**Comment by janl** [comment] 2019-09-24 08:15
Thanks, we’ll investigate

**Comment by Siggnja** [comment] 2019-09-24 08:16
Same for us.

**Comment by janl** [comment] 2019-09-24 11:23
Thanks for your patience, another fix just went live. Leaving this open until confirmed fixed.

**Comment by nojaf** [comment] 2019-09-24 18:31
Looks ok here, https://github.com/nojaf/fable-reactstrap/pull/14/files

**Comment by janl** [comment] 2019-09-27 07:48
Closing this now after no further reports have come in. Feel free to open if this comes up again.

**Closed by janl** 2019-09-27 07:48 UTC
Labels: Bug/Problem
