### ISSUE TITLE
Add support for nested package.json checking

### ISSUE THREAD

**Issue by StephanBijzitter** [greenkeeperio/greenkeeper#308] opened 2016-10-05 07:22 UTC
Hello!

We've recently started using Greenkeeper to keep our private NPM repository up to date, but the effect is limited because we have a structure that is designed to limit maintenance to a minimum.

The root of our project contains a package file with developer dependencies, that are used by all (or a large majority) of our NPM modules. The modules themselves are in a directory called modules.

This means we have package files in the following directories:

- root/package.json
- root/modules/module-a/package.json
- root/modules/module-b/package.json
- et cetera

Currently, Greenkeeper only checks the first package file in the root. I would hereby like to request a configuration option to scan a glob for package files, making the location(s) completely customizable.

I have not yet taken a look at the code, but if you think a third party could implement this, I would be able to get our management to give this more priority, allowing us to create this feature. If that's the case and you already have an idea of where this should be implemented, please do provide us some filenames.

**Comment by rkuykendall** [comment] 2016-10-05 15:35
This appears to be a duplicate of issue https://github.com/greenkeeperio/greenkeeper/issues/139. If so, you should 👍 that issue and add any information you think is helpful to that issue.

**Closed** 2016-10-05 17:06 UTC
