### ISSUE TITLE
Greenkeeper PR version is not correct?

### ISSUE THREAD

**Issue by Siilwyn** [greenkeeperio/greenkeeper#417] opened 2017-05-07 12:02 UTC
Not sure if this belongs here...

Greenkeeper opened [this PR](https://github.com/Siilwyn/css-declaration-sorter/pull/35) stating version `5.2.17 ` is used. However the current version is `6.0.0` as also shown at the [PR diff page](https://github.com/Siilwyn/css-declaration-sorter/pull/35/files).

Any idea how this is possible?

**Comment by boennemann** [comment] 2017-05-21 00:17
Hey @Siilwyn,

sorry about this, it looks like a problem that's caused by out-of-sync package.json content in our database.
This should not happen anymore, so I'll go ahead and close this issue.

Happy to reopen should this happen again.

Best,
Stephan

**Closed by boennemann** 2017-05-21 00:17 UTC
Labels: Bug/Problem
