### ISSUE TITLE
Enable Greenkeeper without repo admin access

### ISSUE THREAD

**Issue by phillipj** [greenkeeperio/greenkeeper#68] opened 2015-11-13 19:01 UTC
Any tips on debugging missing greenkeeper PRs?

As raised by @lpinca in https://github.com/nodejs/new.nodejs.org/issues/355#issuecomment-156492183, we're missing a PR on nodejs.org about `node-version-data` latest patch about 11 hours ago in https://github.com/rvagg/node-version-data/commit/41c3d5ba95a4209e1e0c9c354534bb9c185c3a6b. It's specified with an exact version in our [package.json](https://github.com/nodejs/new.nodejs.org/blob/master/package.json#L43), so it should always create a PR for any new version, right?

**Comment by phillipj** [comment] 2015-11-24 22:10
Just found out we don't allow private access to third-party applications anymore, might that be causing these issues? We're seeing some similar issues with our Travis integration these days..

**Comment by jonathanong** [comment] 2015-12-22 21:44
might be a similar issue - i have a private repo where greenkeeper creates branches but it does not make PRs. how do i fix that?

**Comment by janl** [comment] 2015-12-22 21:46
@jonathanong is your case also with fixed version numbers? If you use ranges, we only open PRs when the build breaks.

@phillipj that might well be possible. We’ll realistically investigate more thoroughly after the holidays.

Thanks for your patience!

**Comment by jonathanong** [comment] 2015-12-22 22:00
@janl ah that must be it. thanks.

**Comment by phillipj** [comment] 2015-12-22 22:43
Thanks @janl, much appreciated! Happy holidays 🎄

**Comment by phillipj** [comment] 2016-05-06 08:52
@janl we'd still love to use greenkeeper.. Have you figured out if you require private access for it to work?

**Comment by janl** [comment] 2016-05-06 10:04
@phillipj oops, sorry, I skimmed issues and thought this was resolved, while it really isn’t yet! We’ll be able to help you very soon, stay tuned! :)

**Comment by phillipj** [comment] 2016-05-06 10:34
Oooh, sounds good! Thanks for the update 👍

**Comment by christophwitzko** [comment] 2016-05-06 11:05
sorry for closing this issue again, but this is a duplicate of https://github.com/greenkeeperio/greenkeeper/issues/46 😊

**Closed by christophwitzko** 2016-05-06 11:05 UTC
Labels: Feature Request, in progress

**Comment by boennemann** [comment] 2016-06-05 11:48
This landed with `greenkeeper@2.13.0` https://github.com/greenkeeperio/greenkeeper/releases/tag/v2.13.0.

Details: https://greenkeeper.io/manual-webhooks.html

Thanks for your patience.

**Comment by lpinca** [comment] 2016-06-05 12:13
Awesome, thanks!

**Comment by lpinca** [comment] 2016-06-05 12:20
cc: @Fishrock123 @mikeal

**Comment by phillipj** [comment] 2016-06-05 21:18
@Ipinca fyi https://github.com/greenkeeperio/greenkeeper/pull/205#issuecomment-223837403

**Comment by Fishrock123** [comment] 2016-06-15 21:30
Is there any action I need to take here?

**Comment by lpinca** [comment] 2016-06-16 05:18
@Fishrock123 I don't think so, @phillipj tried to make it work with no luck so far.

**Comment by Fishrock123** [comment] 2016-06-16 16:24
@lpinca Right, I was asking if there is something concrete we (node.js owners) need to do permissions-wise to help this?

**Comment by lpinca** [comment] 2016-06-16 16:37
Oh, sorry.
