### ISSUE TITLE
Greenkeeper bot has no avatar in commit history

### ISSUE THREAD

**Issue by wopian** [greenkeeperio/greenkeeper#388] opened 2017-03-06 14:32 UTC
Not sure if this is the correct place for this, but I have the following issue in all of my greenkeeper enabled repos:

The greenkeeper bot's avatar which is visible in the PR isn't shown in the commit history, although it is shown besides the latest commit bar. [Repo](https://github.com/wopian/hibari/commits/master)

![](https://i.imgur.com/T2UEEZ5.png)
![](https://i.imgur.com/hdXj7Qh.png)

**Comment by Arcanemagus** [comment] 2017-03-06 17:22
This is essentially a duplicate of https://github.com/greenkeeperio/greenkeeper/issues/329 as it is the root cause.

**Comment by boennemann** [comment] 2017-03-09 10:05
Thanks @Arcanemagus for linking this up and thanks @wopian for reporting.

This is the latest status from GitHub we have:

> Sorry for the delay, and thanks for sharing additional details about how this would be useful. We've decided that this is something that we do plan to add support for. We don't have an estimated time, but we'll update this issue once we have something in place.

I'm closing this as a duplicate now.

Best,
Stephan

**Closed by boennemann** 2017-03-09 10:05 UTC
