### ISSUE TITLE
Feat: Support node.js releases and deprecations

### ISSUE THREAD

**Issue by espy** [greenkeeperio/greenkeeper#710] opened 2018-04-16 14:05 UTC
We’d like to be able to launch jobs that inform people about node.js releases and deprecations, say node 10 gets released, and node 4 reaches end-of-life. 

In these cases, we want to 
- [x] scan for repos with a `travis.yml`
- [ ] check whether node 4 is in there and open an issue for that
- [x] check whether node 10 is _not_ in there and open an issue for that. This includes checking whether `latest` is present and would install 10 etc., we don’t want to send superfluous issues.

Each issue should include a link that opens a PR with the proposed change to the `travis.yml`, just like our update comments do now. We’re not opening PRs directly because we got a bit of pushback the last time we did that.

**Comment by Realtin** [comment] 2018-04-16 14:13
### Specifying Node.js latest release versions
**node** -> latest stable Node.js release
**lts/*** -> latest LTS Node.js release
**lts/Codename** -> Argon = node v.4, codename for v10 not announced yet
**stable** -> deprecated, but is an alias for **node**

since travis uses nvm, you can specify any versions in the travis.yml that can be installed via nvm

```yaml
language: node_js
node_js:
  - "node"
  - "stable"
  - "lts/*"
  - "lts/Codename"
  - "10"
```

### .nvmrc
The .nvmrc file is only read when node_js key in your .travis.yml files does not specify a nodejs version. When the .nvmrc file is read, $TRAVIS_NODE_VERSION is set to the nodejs version.

**Comment by espy** [comment] 2018-04-16 14:48
Ok, so we want to add `10` if the file does _not_ include:
```yaml
node_js:
  - "node"
  - "stable"
  - "10" // or any other version numbers in the `10.x.x` or `10.x` format
```

And we want to remove `4` in any of these forms:
```yaml
node_js:
  - "lts/argon"
  - "4"
  - "4.2.1" // and all other version numbers in the `4.x.x` or `4.x` format
```
[List of node.js releases](https://nodejs.org/en/download/releases/), nothing unexpected there though.

Side note 1: from the Travis docs:

> Specifying Node.js versions using `.nvmrc`
Optionally, your repository can contain a `.nvmrc` file in the repository root to specify which single version of Node.js to run your tests against.

> The `.nvmrc` file is only read when node_js key in your `.travis.yml` files does not specify a nodejs version. When the `.nvmrc` file is read, `$TRAVIS_NODE_VERSION` is set to the nodejs version. See nvm documentation for more information on `.nvmrc`.

Side note 2: if we _do_ want to automate this: https://github.com/nodejs/Release/blob/master/schedule.json

**Comment by travi** [comment] 2018-04-16 21:49
i'm excited to see this make the list. i opened [this related issue](https://github.com/greenkeeperio/greenkeeper/issues/544) a little while back. not sure if there is any additional detail in there that would be helpful, but figured its worth keeping it visible with this.

**Comment by espy** [comment] 2018-04-17 07:51
@travi nice, that’s a good impulse for us to try handling the `.nvmrc` and the engines in `package.json` too, we’ll take a closer look at that today.

**Comment by espy** [comment] 2018-04-17 15:07
`.nvmrc` is just a single version name/number: https://github.com/creationix/nvm#nvmrc

```
$ echo "5.9" > .nvmrc

$ echo "lts/*" > .nvmrc # to default to the latest LTS version

$ echo "node" > .nvmrc # to default to the latest version
```

**Comment by travi** [comment] 2018-04-17 15:31
i think its worth considering that it would probably be helpful for there to be a way to specify an upper bound for desired updates. 

for lts vs latest, it would be nice if that could be specified in the `.nvmrc` file and assume that the `engines` would be updated to be kept in sync with that. i currently keep those in sync manually.

the other case, though, that i don't see the `.nvmrc` being enough to specify the upper bound for is the limit of a deployment target. google cloud functions, for example, are still limited to v6, so i wouldnt want the `.nvmrc` file for those projects to be updated to lts or latest.

**Comment by janl** [comment] 2018-04-17 15:53
@travi heya, all good points!

For the moment, we are planning to do this with major releases and deprecations only (so +10.x and -4.x), so it’ll happen on a regular schedule once or twice per year tops. So this would be less the usual update for every new release, but for now only opting into major stable/LTS release lines and getting off of unsupported versions.

Either way, these will raise issues that users can use to open a PR for the up/downgrade separately, so you can totally stay on Node 6 as the upper bound by closing the issue and not opening a PR.

Does that address your immediate concerns? :)

**Comment by travi** [comment] 2018-04-17 17:04
> these will raise issues that users can use to open a PR for the up/downgrade separately, so you can totally stay on Node 6 as the upper bound by closing the issue and not opening a PR.

this is the key detail, so yes it does address my concerns. my assumption was that the notification would be sent as a PR rather than an issue, like dependency updates. since my use of greenkeeper is on the extreme end with auto merges with greenkeeper-keeper, my thoughts were spinning through the cases to guard against so that merging the PR wouldn't be more aggressive than desirable. the issue is a big help, even without being a PR, but also prevents any need for special handling for preventing an automatic merge.

thanks for the additional detail (or clarifying if i overlooked it). excited to see this move forward :)

**Comment by espy** [comment] 2018-04-25 15:30
For reference: this is what this looks like now for Greenkeeper itself, which has no `.nvmrc`: https://github.com/greenkeeperio/greenkeeper/issues/730

**Closed** 2018-07-10 14:21 UTC
Labels: Feature
