### ISSUE TITLE
bot ruins my package.json :(

### ISSUE THREAD

**Issue by gdi2290** [greenkeeperio/greenkeeper#176] opened 2016-04-26 20:45 UTC
do you think we can have better support for maintaining the whitespace?
https://github.com/AngularClass/angular2-webpack-starter/pull/545/files

**Comment by boennemann** [comment] 2016-04-29 10:10
Hey @gdi2290,

thanks for your feedback on this. I'm closing your issue as a duplicate of https://github.com/greenkeeperio/greenkeeper/issues/123

Please subscribe there to receive updates on the matter.

Best,
Stephan

**Closed by boennemann** 2016-04-29 10:10 UTC
